import { useEffect, useMemo, useState } from 'react';
import http from '../api/http';

const initialForm = { name: '', location: '', basePricePerHour: 1000, image: '', description: '', start: 6, end: 23 };
const formatHour = (hour) => `${hour % 12 || 12}:00 ${hour < 12 ? 'AM' : 'PM'}`;

export default function AdminPage() {
  const [turfs, setTurfs] = useState([]); const [bookings, setBookings] = useState([]); const [form, setForm] = useState(initialForm);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [updatingBooking, setUpdatingBooking] = useState('');
  const [message, setMessage] = useState({ type: '', text: '' }); const [bookingFilters, setBookingFilters] = useState({ search: '', status: 'all', payment: 'all', date: '' });

  const load = async () => { setLoading(true); try { const [turfRes, bookingRes] = await Promise.all([http.get('/turfs/admin/all'), http.get('/bookings/admin/all')]); setTurfs(turfRes.data); setBookings(bookingRes.data); } catch (error) { setMessage({ type: 'error', text: error.response?.data?.message || 'Unable to load admin data.' }); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);

  const stats = useMemo(() => ({ activeTurfs: turfs.filter((t) => t.isActive).length, totalBookings: bookings.length, paidBookings: bookings.filter((b) => b.paymentStatus === 'paid').length, revenue: bookings.filter((b) => b.paymentStatus === 'paid').reduce((sum, b) => sum + Number(b.totalPrice || 0), 0) }), [turfs, bookings]);
  const filteredBookings = useMemo(() => { const search = bookingFilters.search.trim().toLowerCase(); return [...bookings].filter((b) => { const matchesSearch = !search || [b.user?.name, b.user?.email, b.turf?.name, b.turf?.location].filter(Boolean).some((v) => String(v).toLowerCase().includes(search)); return matchesSearch && (bookingFilters.status === 'all' || b.status === bookingFilters.status) && (bookingFilters.payment === 'all' || b.paymentStatus === bookingFilters.payment) && (!bookingFilters.date || b.date === bookingFilters.date); }).sort((a, b) => `${b.date}-${String(b.startHour).padStart(2, '0')}`.localeCompare(`${a.date}-${String(a.startHour).padStart(2, '0')}`)); }, [bookings, bookingFilters]);

  const createTurf = async (e) => { e.preventDefault(); setSaving(true); setMessage({ type: '', text: '' }); try { await http.post('/turfs', { name: form.name, location: form.location, basePricePerHour: Number(form.basePricePerHour), image: form.image, description: form.description, availableHours: { start: Number(form.start), end: Number(form.end) } }); setForm(initialForm); setMessage({ type: 'success', text: 'Turf added successfully.' }); await load(); } catch (error) { setMessage({ type: 'error', text: error.response?.data?.message || 'Unable to add turf.' }); } finally { setSaving(false); } };
  const updateTurf = async (id, payload) => { try { await http.put(`/turfs/${id}`, payload); setMessage({ type: 'success', text: 'Turf updated.' }); await load(); } catch (error) { setMessage({ type: 'error', text: error.response?.data?.message || 'Unable to update turf.' }); } };
  const updateStatus = async (booking, status) => { if (status === 'cancelled') { const refundText = booking.paymentStatus === 'paid' ? ' This will also initiate the Razorpay refund.' : ''; if (!window.confirm(`Cancel this booking?${refundText}`)) return; } setUpdatingBooking(booking._id); setMessage({ type: '', text: '' }); try { const response = await http.put(`/bookings/admin/${booking._id}/status`, { status }); setMessage({ type: 'success', text: response.data?.message || `Booking ${status}.` }); await load(); } catch (error) { setMessage({ type: 'error', text: error.response?.data?.message || 'Unable to update booking.' }); } finally { setUpdatingBooking(''); } };
  const deactivate = async (turf) => { try { if (turf.isActive) await http.delete(`/turfs/${turf._id}`); else await http.put(`/turfs/${turf._id}`, { isActive: true }); setMessage({ type: 'success', text: turf.isActive ? 'Turf deactivated.' : 'Turf activated.' }); await load(); } catch (error) { setMessage({ type: 'error', text: error.response?.data?.message || 'Unable to change turf status.' }); } };
  const resetFilters = () => setBookingFilters({ search: '', status: 'all', payment: 'all', date: '' });

  return <div className="space-y-7 pb-10">
    <section className="premium-card relative overflow-hidden p-6 sm:p-8"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-green-500/10 blur-3xl" /><div className="relative"><p className="text-xs font-black uppercase tracking-[0.22em] text-green-600 dark:text-green-400">Control centre</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Admin Dashboard</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-gray-500 dark:text-gray-400">Run the venue from one clean workspace — pricing, turf availability, customer bookings and payments.</p></div></section>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Active turfs', stats.activeTurfs, 'Live venues'], ['Bookings', stats.totalBookings, 'All sessions'], ['Paid bookings', stats.paidBookings, 'Successful payments'], ['Net revenue', `₹${stats.revenue}`, 'Paid & non-refunded']].map(([label, value, sub]) => <div key={label} className="premium-card p-5"><div className="flex items-start justify-between"><p className="text-sm font-semibold text-gray-500">{label}</p><span className="h-2.5 w-2.5 rounded-full bg-green-500" /></div><p className="mt-3 text-2xl font-black tracking-tight">{value}</p><p className="mt-1 text-xs text-gray-400">{sub}</p></div>)}</div>
    {message.text && <div role="status" className={`rounded-2xl border px-4 py-3 text-sm font-semibold ${message.type === 'success' ? 'border-green-200 bg-green-50 text-green-700 dark:border-green-900/60 dark:bg-green-950/20 dark:text-green-300' : 'border-red-200 bg-red-50 text-red-700 dark:border-red-900/60 dark:bg-red-950/20 dark:text-red-300'}`}>{message.type === 'success' ? '✓ ' : '⚠ '}{message.text}</div>}

    <form onSubmit={createTurf} className="premium-card grid gap-4 p-5 sm:p-6 sm:grid-cols-2 lg:grid-cols-3"><div className="sm:col-span-2 lg:col-span-3"><p className="text-xs font-black uppercase tracking-wider text-green-600 dark:text-green-400">Venue management</p><h2 className="mt-1 text-xl font-black">Add a new turf</h2></div>
      <label className="text-sm font-bold">Turf name<input required placeholder="e.g. Elite Arena" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="field mt-2" /></label>
      <label className="text-sm font-bold">Location<input required placeholder="Venue location" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} className="field mt-2" /></label>
      <label className="text-sm font-bold">Price / hour<input type="number" min="1" required value={form.basePricePerHour} onChange={(e) => setForm({ ...form, basePricePerHour: e.target.value })} className="field mt-2" /></label>
      <label className="text-sm font-bold">Image URL<input placeholder="Optional" value={form.image} onChange={(e) => setForm({ ...form, image: e.target.value })} className="field mt-2" /></label>
      <label className="text-sm font-bold">Description<input placeholder="Short venue description" maxLength="1000" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="field mt-2" /></label>
      <div><p className="text-sm font-bold">Opening hours</p><div className="mt-2 grid grid-cols-2 gap-3"><input type="number" min="0" max="23" value={form.start} onChange={(e) => setForm({ ...form, start: e.target.value })} className="field" aria-label="Opening hour" /><input type="number" min="1" max="24" value={form.end} onChange={(e) => setForm({ ...form, end: e.target.value })} className="field" aria-label="Closing hour" /></div></div>
      <button disabled={saving} className="premium-button justify-center py-3 sm:col-span-2 lg:col-span-3">{saving ? 'Adding turf…' : '+ Add Turf'}</button>
    </form>

    <section className="space-y-4"><div><p className="text-xs font-black uppercase tracking-wider text-green-600 dark:text-green-400">Inventory</p><h2 className="mt-1 text-xl font-black">Manage turfs</h2></div>{loading ? <div className="h-32 animate-pulse rounded-3xl bg-gray-200 dark:bg-gray-800" /> : turfs.map((t) => <div key={t._id} className="premium-card p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><p className="font-black">{t.name}</p><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${t.isActive ? 'bg-green-100 text-green-700 dark:bg-green-950/40 dark:text-green-300' : 'bg-gray-100 text-gray-500 dark:bg-gray-800'}`}>{t.isActive ? 'Active' : 'Inactive'}</span></div><p className="mt-1 text-sm text-gray-500">{t.location} · {formatHour(t.availableHours.start)}–{formatHour(t.availableHours.end)}</p></div><div className="flex flex-wrap items-center gap-2"><input defaultValue={t.basePricePerHour} type="number" min="1" className="field w-32" aria-label={`Price for ${t.name}`} onBlur={(e) => updateTurf(t._id, { basePricePerHour: Number(e.target.value) })} /><button onClick={() => deactivate(t)} className={`rounded-xl px-3 py-2 text-sm font-bold transition hover:-translate-y-0.5 ${t.isActive ? 'border border-red-200 text-red-600 dark:border-red-900' : 'bg-green-600 text-white'}`}>{t.isActive ? 'Deactivate' : 'Activate'}</button></div></div></div>)}</section>

    <section className="space-y-4"><div><p className="text-xs font-black uppercase tracking-wider text-green-600 dark:text-green-400">Operations</p><h2 className="mt-1 text-xl font-black">All bookings</h2><p className="mt-1 text-sm text-gray-500">Search, filter and safely manage customer sessions.</p></div>
      <div className="premium-card grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4"><input value={bookingFilters.search} onChange={(e) => setBookingFilters({ ...bookingFilters, search: e.target.value })} placeholder="Search customer or turf" className="field lg:col-span-2" aria-label="Search bookings" /><select value={bookingFilters.status} onChange={(e) => setBookingFilters({ ...bookingFilters, status: e.target.value })} className="field"><option value="all">All booking statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="cancelled">Cancelled</option></select><select value={bookingFilters.payment} onChange={(e) => setBookingFilters({ ...bookingFilters, payment: e.target.value })} className="field"><option value="all">All payment statuses</option><option value="paid">Paid</option><option value="refunded">Refunded</option><option value="pending">Payment pending</option><option value="failed">Payment failed</option></select><input type="date" value={bookingFilters.date} onChange={(e) => setBookingFilters({ ...bookingFilters, date: e.target.value })} className="field" aria-label="Filter booking date" /><button type="button" onClick={resetFilters} className="rounded-xl border px-4 py-3 text-sm font-bold transition hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-gray-800">Clear filters</button><p className="flex items-center text-sm text-gray-500 sm:col-span-2 lg:col-span-2">Showing <span className="mx-1 font-black text-gray-900 dark:text-white">{filteredBookings.length}</span> of {bookings.length}</p></div>
      {!loading && !bookings.length && <div className="premium-card border-dashed p-8 text-center text-sm text-gray-500">No bookings yet.</div>}{!loading && bookings.length > 0 && !filteredBookings.length && <div className="premium-card border-dashed p-8 text-center text-sm text-gray-500">No bookings match these filters.</div>}
      {filteredBookings.map((b) => { const updating = updatingBooking === b._id; return <div key={b._id} className="premium-card p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-black">{b.user?.name || 'User'} · {b.turf?.name || 'Turf'}</p><span className="rounded-full bg-gray-100 px-2.5 py-1 text-[11px] font-bold capitalize dark:bg-gray-800">{b.status}</span></div>{b.user?.email && <p className="mt-1 text-xs text-gray-500">{b.user.email}</p>}<p className="mt-2 text-sm text-gray-500">{b.date} · {formatHour(b.startHour)}–{formatHour(b.endHour)} · <span className="font-bold text-gray-800 dark:text-gray-200">₹{b.totalPrice}</span></p><div className="mt-2 flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${b.paymentStatus === 'refunded' ? 'bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300' : b.paymentStatus === 'paid' ? 'bg-green-50 text-green-700 dark:bg-green-950/40 dark:text-green-300' : 'bg-gray-100 dark:bg-gray-800'}`}>payment: {b.paymentStatus}</span>{b.refundStatus && b.refundStatus !== 'not_applicable' && <span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">refund: {b.refundStatus}</span>}</div></div><div className="flex shrink-0 gap-2">{b.status !== 'approved' && b.status !== 'cancelled' && <button disabled={updating} onClick={() => updateStatus(b, 'approved')} className="rounded-xl bg-green-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{updating ? 'Updating…' : 'Approve'}</button>}{b.status !== 'cancelled' && <button disabled={updating} onClick={() => updateStatus(b, 'cancelled')} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-600 disabled:opacity-50 dark:border-red-900">{updating ? 'Updating…' : 'Cancel'}</button>}</div></div></div>; })}
    </section>
  </div>;
}
