import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import http from '../api/http';
import { useAuth } from '../context/AuthContext';

const formatHour = (hour) => `${hour % 12 || 12}:00 ${hour < 12 ? 'AM' : 'PM'}`;
const getLocalDate = () => { const now = new Date(); const offset = now.getTimezoneOffset(); return new Date(now.getTime() - offset * 60 * 1000).toISOString().slice(0, 10); };
const loadRazorpay = () => new Promise((resolve, reject) => { if (window.Razorpay) return resolve(true); const script = document.createElement('script'); script.src = 'https://checkout.razorpay.com/v1/checkout.js'; script.onload = () => resolve(true); script.onerror = () => reject(new Error('Unable to load payment checkout.')); document.body.appendChild(script); });
const TURF_IMAGE_FALLBACK = '/turf-placeholder.svg';

export default function HomePage() {
  const [turfs, setTurfs] = useState([]), [availability, setAvailability] = useState(null), [availabilityLoading, setAvailabilityLoading] = useState(false);
  const [form, setForm] = useState({ turfId: '', date: getLocalDate(), startHour: 18, endHour: 19, notes: '' });
  const [message, setMessage] = useState({ type: '', text: '' }), [loading, setLoading] = useState(true), [booking, setBooking] = useState(false);
  const { user } = useAuth();
  const minDate = getLocalDate();

  useEffect(() => { http.get('/turfs').then(({ data }) => { setTurfs(data); if (data[0]) { const first = data[0]; const startHour = Math.min(Math.max(18, first.availableHours?.start ?? 6), (first.availableHours?.end ?? 23) - 1); setForm((prev) => ({ ...prev, turfId: first._id, startHour, endHour: startHour + 1 })); } }).catch(() => setMessage({ type: 'error', text: 'Unable to load turfs. Please refresh.' })).finally(() => setLoading(false)); }, []);
  const selectedTurf = useMemo(() => turfs.find((t) => t._id === form.turfId), [turfs, form.turfId]);
  const start = Number(form.startHour), end = Number(form.endHour), duration = Math.max(0, end - start), totalPrice = selectedTurf && duration ? duration * selectedTurf.basePricePerHour : 0;
  const refreshAvailability = async () => { if (!form.turfId || !form.date) return; setAvailabilityLoading(true); try { const { data } = await http.get('/bookings/availability', { params: { turfId: form.turfId, date: form.date } }); setAvailability(data); const available = data.availableHours || []; const current = available.includes(Number(form.startHour)); const nextStart = current ? Number(form.startHour) : available[0]; if (nextStart !== undefined) setForm((prev) => ({ ...prev, startHour: nextStart, endHour: nextStart + 1 })); } catch { setAvailability(null); setMessage({ type: 'error', text: 'Could not refresh availability. Please try again.' }); } finally { setAvailabilityLoading(false); } };
  useEffect(() => { refreshAvailability(); }, [form.turfId, form.date]);
  const isRangeAvailable = (rangeStart, rangeEnd) => { if (!availability) return true; for (let hour = rangeStart; hour < rangeEnd; hour += 1) if (!availability.availableHours?.includes(hour)) return false; return true; };
  const startOptions = selectedTurf ? Array.from({ length: Math.max(0, selectedTurf.availableHours.end - selectedTurf.availableHours.start - 1) }, (_, i) => selectedTurf.availableHours.start + i).filter((h) => !availability || availability.availableHours?.includes(h)) : [];
  const endOptions = selectedTurf ? Array.from({ length: Math.max(0, selectedTurf.availableHours.end - start) }, (_, i) => start + 1 + i).filter((h) => isRangeAvailable(start, h)) : [];
  const confirmMockBooking = async (bookingData) => { const payment = await http.post('/bookings/confirm-payment', { bookingId: bookingData.booking._id, razorpayOrderId: bookingData.order.id, razorpayPaymentId: `mock_payment_${Date.now()}` }); setMessage({ type: 'success', text: payment.data.message }); };
  const openRazorpay = async (bookingData) => { await loadRazorpay(); if (!bookingData.razorpayKeyId) throw new Error('Payment configuration is missing.'); await new Promise((resolve, reject) => { const checkout = new window.Razorpay({ key: bookingData.razorpayKeyId, amount: bookingData.order.amount, currency: bookingData.order.currency, name: 'TurfBook', description: `${selectedTurf.name} • ${bookingData.booking.duration} hour(s)`, order_id: bookingData.order.id, prefill: { name: user?.name || '', email: user?.email || '', contact: user?.phone || '' }, theme: { color: '#16a34a' }, handler: async (response) => { try { const payment = await http.post('/bookings/confirm-payment', { bookingId: bookingData.booking._id, razorpayOrderId: response.razorpay_order_id, razorpayPaymentId: response.razorpay_payment_id, razorpaySignature: response.razorpay_signature }); setMessage({ type: 'success', text: payment.data.message }); resolve(); } catch (error) { reject(new Error(error.response?.data?.message || 'Payment verification failed.')); } }, modal: { ondismiss: () => reject(new Error('Payment was cancelled. Your slot is held temporarily and will expire automatically.')) } }); checkout.on('payment.failed', (response) => reject(new Error(response.error?.description || 'Payment failed.'))); checkout.open(); }); };
  const handleBooking = async (e) => { e.preventDefault(); setMessage({ type: '', text: '' }); if (!user) return setMessage({ type: 'error', text: 'Please login or register before booking.' }); if (!selectedTurf || end <= start) return setMessage({ type: 'error', text: 'Please choose a valid time range.' }); if (!startOptions.length || !endOptions.length) return setMessage({ type: 'error', text: 'No valid slot is available. Please choose another time or date.' }); if (!isRangeAvailable(start, end)) return setMessage({ type: 'error', text: 'One or more selected hours are no longer available. Refresh the slot list and try again.' }); setBooking(true); try { const { data } = await http.post('/bookings', form); if (data.mockPayment) await confirmMockBooking(data); else await openRazorpay(data); setForm((prev) => ({ ...prev, notes: '' })); await refreshAvailability(); } catch (error) { setMessage({ type: 'error', text: error.response?.data?.message || error.message || 'Booking failed. Please try again.' }); } finally { setBooking(false); } };
  const setTurf = (turfId) => { const turf = turfs.find((t) => t._id === turfId); const startHour = Math.min(Math.max(18, turf?.availableHours?.start ?? 6), (turf?.availableHours?.end ?? 23) - 1); setAvailability(null); setForm((prev) => ({ ...prev, turfId, startHour, endHour: startHour + 1 })); };
  const chooseStart = (value) => { const next = Number(value); setForm((prev) => ({ ...prev, startHour: next, endHour: next + 1 })); };

  return <div className="space-y-12 pb-10">
    <section className="relative isolate overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-14 text-white shadow-2xl shadow-slate-900/20 sm:px-10 sm:py-20"><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full bg-green-500/20 blur-3xl" /><div className="absolute -bottom-32 left-1/3 h-72 w-72 rounded-full bg-emerald-500/10 blur-3xl" /><div className="relative max-w-3xl animate-fade-up"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-green-400/20 bg-green-400/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.18em] text-green-300"><span className="h-2 w-2 animate-pulse rounded-full bg-green-400" /> Live turf booking</div><h1 className="text-5xl font-black tracking-[-0.04em] sm:text-7xl">Play more.<br /><span className="bg-gradient-to-r from-green-300 via-emerald-400 to-green-500 bg-clip-text text-transparent">Book smarter.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">Premium football turfs, live availability and secure checkout — everything you need to get your next match on the calendar.</p>{!user && <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/register" className="premium-button inline-flex items-center justify-center">Create free account <span className="ml-2">→</span></Link><a href="#booking" className="inline-flex items-center justify-center rounded-xl border border-white/15 bg-white/5 px-5 py-3 font-bold text-white backdrop-blur transition hover:bg-white/10">Book a turf</a></div>}</div><div className="relative mt-12 grid max-w-2xl grid-cols-3 gap-3 sm:gap-5">{[['⚡','Fast booking'],['✓','Live availability'],['🔒','Secure payment']].map(([icon,label]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/5 p-4 backdrop-blur-md"><div className="text-lg">{icon}</div><p className="mt-2 text-xs font-semibold text-slate-300 sm:text-sm">{label}</p></div>)}</div></section>

    <section id="turfs"><div className="mb-5 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-green-600">Choose your pitch</p><h2 className="mt-1 text-3xl font-black tracking-tight">Available turfs</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Professional spaces ready for your next game.</p></div><span className="hidden rounded-full bg-green-50 px-3 py-1.5 text-xs font-bold text-green-700 dark:bg-green-950/40 dark:text-green-300 sm:inline-flex">{turfs.length} {turfs.length === 1 ? 'turf' : 'turfs'}</span></div>{loading ? <div className="grid gap-5 sm:grid-cols-2"><div className="h-80 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800" /><div className="h-80 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800" /></div> : turfs.length === 0 ? <div className="premium-card border-dashed p-10 text-center text-slate-500">No active turfs are available right now.</div> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{turfs.map((turf, index) => <article key={turf._id} className="premium-card group animate-fade-up overflow-hidden" style={{ animationDelay: `${index * 80}ms` }}><div className="relative overflow-hidden"><img src={turf.image || TURF_IMAGE_FALLBACK} onError={(e) => { e.currentTarget.onerror = null; e.currentTarget.src = TURF_IMAGE_FALLBACK; }} alt={turf.name} className="h-52 w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/40 via-transparent to-transparent" /><span className="absolute right-3 top-3 rounded-full border border-white/20 bg-slate-950/70 px-3 py-1.5 text-sm font-black text-white backdrop-blur">₹{turf.basePricePerHour}/hr</span></div><div className="p-5"><h3 className="text-xl font-black">{turf.name}</h3><p className="mt-1 text-sm font-medium text-slate-500">📍 {turf.location}</p><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{turf.description || 'Quality football turf for your next match.'}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4 text-xs font-semibold text-slate-500 dark:border-slate-800"><span>⏱ Open {formatHour(turf.availableHours?.start ?? 6)} – {formatHour(turf.availableHours?.end ?? 23)}</span><button type="button" onClick={() => { setTurf(turf._id); document.getElementById('booking')?.scrollIntoView({ behavior: 'smooth' }); }} className="font-bold text-green-600 transition hover:text-green-500">Book this →</button></div></div></article>)}</div>}</section>

    <section id="booking" className="premium-card relative overflow-hidden p-5 sm:p-8"><div className="absolute -right-20 -top-20 h-52 w-52 rounded-full bg-green-500/10 blur-3xl" /><div className="relative mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-green-600">Reserve your time</p><h2 className="mt-1 text-3xl font-black tracking-tight">Book a slot</h2><p className="mt-1 max-w-2xl text-sm text-slate-500 dark:text-slate-400">Choose a pitch, date and available hours. Your slot is held for 15 minutes during checkout.</p></div><div className="rounded-2xl border border-green-100 bg-green-50 px-4 py-3 dark:border-green-900/50 dark:bg-green-950/30"><p className="text-[11px] font-bold uppercase tracking-wider text-green-700 dark:text-green-300">Live status</p><p className="mt-0.5 text-sm font-black text-green-800 dark:text-green-200">{availabilityLoading ? 'Checking slots…' : availability ? `${availability.availableHours?.length || 0} hours open` : 'Select a date'}</p></div></div>
      <form onSubmit={handleBooking} className="relative space-y-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Turf<select className="field mt-1.5" value={form.turfId} onChange={(e) => setTurf(e.target.value)} required>{turfs.map((t) => <option value={t._id} key={t._id}>{t.name} • ₹{t.basePricePerHour}/hr</option>)}</select></label><label className="text-sm font-semibold">Date<input type="date" min={minDate} className="field mt-1.5" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} required /></label></div>
        <div><div className="mb-3 flex items-center justify-between"><p className="text-sm font-bold">Choose start time</p><span className="text-xs font-medium text-slate-500">{availabilityLoading ? 'Updating…' : 'Green slots are available'}</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-6">{selectedTurf && Array.from({ length: Math.max(0, selectedTurf.availableHours.end - selectedTurf.availableHours.start - 1) }, (_, i) => selectedTurf.availableHours.start + i).map((hour) => { const available = !availability || availability.availableHours?.includes(hour); const active = start === hour; return <button type="button" key={hour} disabled={!available || availabilityLoading} onClick={() => chooseStart(hour)} className={`rounded-xl border px-3 py-3 text-left transition ${active ? 'border-green-600 bg-green-600 text-white shadow-lg shadow-green-600/20' : available ? 'border-slate-200 bg-white hover:-translate-y-0.5 hover:border-green-300 hover:text-green-700 dark:border-slate-700 dark:bg-slate-900' : 'cursor-not-allowed border-slate-100 bg-slate-50 text-slate-300 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-700'}`}><span className="block text-xs font-bold">{available ? 'AVAILABLE' : 'BOOKED'}</span><span className="mt-1 block text-sm font-black">{formatHour(hour)}</span></button>; })}</div></div>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">End time<select className="field mt-1.5" value={end} onChange={(e) => setForm({ ...form, endHour: Number(e.target.value) })} disabled={availabilityLoading || !endOptions.length} required>{endOptions.map((hour) => <option key={hour} value={hour}>{formatHour(hour)}</option>)}</select></label><label className="text-sm font-semibold">Notes <span className="font-normal text-slate-400">(optional)</span><input className="field mt-1.5" placeholder="e.g. 10 players, league match" maxLength="200" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div>
        <div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-900/70"><div className="flex flex-wrap items-center gap-x-6 gap-y-3"><div><p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Pitch</p><p className="mt-1 font-black">{selectedTurf?.name || '—'}</p></div><div><p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Time</p><p className="mt-1 font-black">{selectedTurf && duration ? `${formatHour(start)} – ${formatHour(end)}` : '—'}</p></div><div><p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Duration</p><p className="mt-1 font-black">{duration ? `${duration} hour${duration === 1 ? '' : 's'}` : '—'}</p></div><div className="ml-auto min-w-[150px] text-right"><p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Total</p><p className="mt-0.5 text-2xl font-black text-green-600">₹{totalPrice}</p></div></div></div><button disabled={booking || availabilityLoading || !turfs.length || !startOptions.length || !endOptions.length} className="premium-button min-w-[190px]">{booking ? 'Opening checkout…' : 'Continue to payment →'}</button></div>
      </form>
      <div className="relative mt-5 flex flex-col gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:items-center sm:justify-between dark:border-slate-800">{!availabilityLoading && availability && !startOptions.length ? <p className="rounded-xl bg-amber-50 px-4 py-3 text-sm font-medium text-amber-800 dark:bg-amber-950/30 dark:text-amber-200">No hourly slots are available for this date. Please choose another date.</p> : <p className="text-xs text-slate-500">Secure Razorpay checkout • Your slot is held temporarily during payment.</p>}<button type="button" onClick={refreshAvailability} disabled={availabilityLoading || booking} className="shrink-0 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold shadow-sm transition hover:-translate-y-0.5 hover:border-green-300 hover:text-green-700 disabled:opacity-50 dark:border-slate-700 dark:bg-slate-900">{availabilityLoading ? 'Checking…' : 'Refresh availability'}</button></div>
      {message.text && <div role="status" className={`relative mt-4 rounded-xl px-4 py-3 text-sm font-semibold ${message.type === 'success' ? 'bg-green-50 text-green-700 dark:bg-green-950/30 dark:text-green-300' : 'bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-300'}`}>{message.text}</div>}
    </section>
  </div>;
}
